server:
  port: 8080

access_token:
  ttl: 86400000 # 1 day(테스트용

account:
  re-signup-waiting-days: 30 # 탈퇴 후 재가입 대기 기간 (일)

jwt:
  secret-key: test-jwt-secret-key-for-testing

password:
  secret-key: testpasswordaes!

portone:
  store-id: test-store-id
  auth-token: test-auth-token

spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
